<a href="https://colab.research.google.com/github/Ghost0734/fake-news-detector-/blob/main/fake_news_detector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files.upload()  # select the kaggle.json file from your downloads

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"ghost0734","key":"32c111bb07fa06d2f879a6cd1d1854d8"}'}

In [6]:
!git config --global user.email "abhishek180905sharma@gmail.com"
!git config --global user.name "Ghost0734"

In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
print("Kaggle ready!")

Kaggle ready!

In [3]:
!kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset
!unzip fake-and-real-news-dataset.zip

Dataset URL: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset
License(s): CC-BY-NC-SA-4.0
Downloading fake-and-real-news-dataset.zip to /content
  0% 0.00/41.0M [00:00<?, ?B/s]
100% 41.0M/41.0M [00:00<00:00, 1.47GB/s]
Archive:  fake-and-real-news-dataset.zip
  inflating: Fake.csv
  inflating: True.csv

In [15]:
%cd /content/fake-news-detector
!git commit -m "Loaded Data"

[Errno 2] No such file or directory: '/content/fake-news-detector'
/content
fatal: not a git repository (or any of the parent directories): .git

In [13]:
import pandas as pd

fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

print("Fake news articles:", len(fake))
print("Real news articles:", len(true))
fake.head()

Fake news articles: 23481
Real news articles: 21417

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [16]:
# Label the data
fake['label'] = 0   # 0 = Fake
true['label'] = 1   # 1 = Real

# Combine and shuffle
df = pd.concat([fake, true]).sample(frac=1).reset_index(drop=True)
print("Total articles:", len(df))
print(df['label'].value_counts())
df.head()

Total articles: 44898
label
0    23481
1    21417
Name: count, dtype: int64

,title,text,subject,date,label
0,Brazil poll shows Temer approval plummets on n...,BRASILIA (Reuters) - The approval rating for B...,worldnews,"September 28, 2017",1
1,Argentina faces 'hope and hopelessness' in sub...,BUENOS AIRES (Reuters) - No sign of the Argent...,worldnews,"November 25, 2017",1
2,FLASHBACK: NANCY PELOSI TO ADOPTED WOMAN: Your...,PELOSI CALLED ABORTION A MANHOOD THING :House...,politics,"Feb 4, 2017",0
3,"'Day of Rage' - a knife, a fake bomb belt, a d...","NEAR RAMALLAH, West Bank (Reuters) - I went to...",worldnews,"December 15, 2017",1
4,Democrats Launch Plan To Make Trump’s First S...,Alleged president Donald Trump has literally m...,News,"February 2, 2017",0

In [17]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = ' '.join([w for w in text.split() if w not in stop_words])
    return text

df['text'] = df['text'].apply(clean_text)
print("Cleaning done!")
df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

Cleaning done!

,title,text,subject,date,label
0,Brazil poll shows Temer approval plummets on n...,brasilia reuters approval rating brazilian pre...,worldnews,"September 28, 2017",1
1,Argentina faces 'hope and hopelessness' in sub...,buenos aires reuters sign argentine submarine ...,worldnews,"November 25, 2017",1
2,FLASHBACK: NANCY PELOSI TO ADOPTED WOMAN: Your...,pelosi called abortion manhood thing house min...,politics,"Feb 4, 2017",0
3,"'Day of Rage' - a knife, a fake bomb belt, a d...",near ramallah west bank reuters went road outs...,worldnews,"December 15, 2017",1
4,Democrats Launch Plan To Make Trump’s First S...,alleged president donald trump literally mocke...,News,"February 2, 2017",0